public class ExpendituresServiceModel {
    public String id;
    public Decimal amount;
    public String category;
    public String description;
    public Long expenseDateTime;

    public ExpendituresServiceModel() {
        this.id = id;
        this.amount = amount;
        this.category = category;
        this.description = description;
        this.expenseDateTime = expenseDateTime;
    }
}