name: On merge to master - deploy

on:
    push:
        branches:
            - master

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:

            # Checkout latest from pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Build and deploy
            - name: 'Build and Deploy'
              uses: tiagonnascimento/sfdx-orgdev-build-deploy@v2
              with:
                type: 'production'
                certificate_path: devops/server.key.enc
                decryption_key: ${{ secrets.DECRYPTION_KEY }}
                decryption_iv: ${{ secrets.DECRYPTION_IV }}
                client_id: ${{ secrets.CONSUMER_KEY }}
                username: ${{ secrets.USERNAME }}
                checkonly: false
                deploy_wait_time: '10'
                manifest_path: manifest/package-deploy.xml
                deploy_testlevel: RunSpecifiedTests
                default_source_path: force-app/main/default